### ISSUE TITLE
Cucumber feature error - help me

### ISSUE THREAD

**Issue by kburk1997** [YACS-RCOS/yacs-admin#45]
When I go to the course page for 0                                       # features/step_definitions/webrat_steps.rb:10
      expected an attributes Hash, got ["id", "0"] (ArgumentError)
      ./app/controllers/course_controller.rb:19:in `show'
      ./features/step_definitions/webrat_steps.rb:12:in `/^I go to (.+)$/'
      features/manage_courses.feature:15:in `When I go to the course page for 0'
    Then I should see "Physics"                                              # features/step_definitions/webrat_steps.rb:94

This is the error I get

**Comment by kburk1997** [comment]
I'm taking a new approach:

Turns out the nested resource was screwing with this. Once I commented out the nested resource stuff, everything worked fine. Once the steps for creating each resource in the mock are completed, we'll try this again.

**Comment by kburk1997** [comment]
It seems that .find(:all) is causing this error. When I use find with an ID, it works just fine.
