### ISSUE TITLE
Scenario: Search For a Course

### ISSUE THREAD

**Issue by kburk1997** [YACS-RCOS/yacs-admin#48]
Now that course table, show courses (with a few modifications to the show course page), and search courses homepage features all pass, create a scenario to search for a course.

**Comment by kburk1997** [comment]
Currently getting the following error (this was mentioned in #45 ):

```
  Scenario: Search for a Course            # features/manage_courses.feature:47
    Given the following courses exist      # features/step_definitions/course_steps.rb:112
      | id | name      | number | min_credits | max_credits | description     | department_id |
      | 0  | Calculus  | 1000   | 4           | 4           | Differentiation | 0             |
      | 1  | Physics   | 1000   | 4           | 4           | Mechanics       | 1             |
      | 2  | Chemistry | 1000   | 4           | 4           | Basic chem      | 1             |
    When I go to the course search page    # features/step_definitions/webrat_steps.rb:10
    And I fill in "query" with "Chemistry" # features/step_definitions/webrat_steps.rb:23
    And I press "search-btn"               # features/step_definitions/webrat_steps.rb:15
      expected an attributes Hash, got ["id", "2"] (ArgumentError)
      ./app/controllers/course_controller.rb:40:in `search'
      ./features/step_definitions/webrat_steps.rb:16:in `/^I press "([^\"]*)"$/'
      features/manage_courses.feature:55:in `And I press "search-btn"'
    Then I should see "Chemistry"          # features/step_definitions/webrat_steps.rb:94
```

Here is the relevant course_controller code:

```
  def search
    @query=params[:query] # This global is for the view
    #puts @query
    if params[:query] != "" and params[:query] !=nil then
      #puts @query
      #puts @query==''
      #puts @query==nil
      search_params={:search => @query}
      #puts search_params[:search]
      #Search courses
      puts Course.find(:all, :params=>search_params)
      @courses=Course.find(:all, :params=>search_params).elements
    else
      @courses=''
    end
  end
```

**Comment by kburk1997** [comment]
@Bad-Science any suggestions?
